POST http://localhost:3001/api/users
Authorization: api_key 8HUPPTsuMVVQYYvr6ibbwZLSkkxpuqHeFmJh9Wn93s5uiCBpWGnbe5a5xdQfrr2g
Content-Type: application/json

{
    "admin": true,
	"contactAddress": "Testitie 1",
	"contactCity": "Vantaa",
    "contactCountry": "Suomi",
    "contactFirstName": "Teppo",
    "contactLastName": "Testaaja",
    "contactOrganization": "Testi Oy",
    "contactPhone": "040-1234567",    
    "contactZipcode": "01600",
    "disabled": false,
    "username": "teppo@testaaja.com"
}