name: Deployment pipeline

on:
    push:
        branches:
            - main

jobs:
    deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install dependencies
              run: |
                  npm install --prefix project-backend
                  npm install --prefix project-frontend
            - name: Lint
              run: |
                  npm run lint --prefix project-backend
                  npm run lint --prefix project-frontend
            - name: Build
              env:
                  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
              run: |
                  cd project-frontend
                  npm run build
                  cp -r ./dist ../project-backend/dist
                  cd ..
                  cd project-backend
                  npm run tsc
                  ls -l
            - name: e2e tests
              uses: cypress-io/github-action@v5
              env:
                  API_KEY: ${{ secrets.API_KEY }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  PAYTRAIL_TEST_ACCOUNT: ${{ secrets.PAYTRAIL_TEST_ACCOUNT }}
                  PAYTRAIL_TEST_SECRET: ${{ secrets.PAYTRAIL_TEST_SECRET }}
                  PORT: ${{ secrets.PORT }}
                  SECRET: ${{ secrets.SECRET }}       
                  VITE_ENV: 'test'                             
              with:
                  command: npm run test:e2e
                  start: npm run start --prefix project-backend
                  wait-on: http://localhost:3001
            - name: Trigger deployment
              run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
                  